[versions]
libVersion = "0.0.1"

[libraries]
#validation
jakartaValidation = { module = "jakarta.validation:jakarta.validation-api", version = "3.0.0" }
# testing
mockitoCore = { module = "org.mockito:mockito-core", version = "3.10.0" }
mockitoJunit = { module = "org.mockito:mockito-junit-jupiter", version = "3.9.0" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.6.0" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine" }
assertJ = { module = "org.assertj:assertj-core", version = "3.19.0" }
vintageEngine = { module = "org.junit.vintage:junit-platform-engine", version = "5.1.0" }